### ISSUE TITLE
Simulate

### ISSUE THREAD

**Issue by fossil22** [koraykarakus/steemnova-1.8-x#12] opened 2023-11-24 17:49 UTC
In the spionage report. Simulate combat. Comes on the teaching page. No simulation.

**Comment by koraykarakus** [comment] 2023-11-25 15:19
tested and it seems it is working correctly on GoW theme. Are you sure the problem is on GoW theme ?

**Comment by fossil22** [comment] 2023-11-25 16:43
Hello Yes GOW Theme.
Admin becomes info Massage.
[25-Nov-2023 17:39:39] DEPRECATED ERROR: "Implicit conversion from float 880.0000000000001 to int loses precision"
File: /www/htdocs/w01d6/mkmatz.eno-intern.de/includes/classes/missions/functions/SteemNova_Array.php | Line: 64
URL: https://mkmatz.eno-intern.de/game.php?page=battleSimulator&mode=send | Version: 1.8.git
Stack trace:
#0 [internal function]: errorHandler(8192, 'Implicit conver...', '/www/htdocs/w01...', 64)
#1 /includes/classes/missions/functions/SteemNova_Array.php(64): rand(0, 880.0)
#2 /includes/classes/missions/functions/SteemNova_Array.php(268): explodeAndDestroy(Array)
#3 /includes/pages/game/ShowBattleSimulatorPage.class.php(129): calculateAttack(Array, Array, 30, 0)
#4 /game.php(58): ShowBattleSimulatorPage->send()
#5 {main}

**Comment by fossil22** [comment] 2023-11-25 19:26
Danke für den Fix

**Comment by koraykarakus** [comment] 2023-11-25 20:23
thank you for reporting, it should be fixed.

**Closed by koraykarakus** 2023-11-25 20:23 UTC
